apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-origin: https://{{ .Values.domain }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
  generation: 1
  name: ingress
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service: 
            name: {{ .Release.Name }}-bgio
            port:
              number: 80
        path: /socket.io/
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Release.Name }}-fbg-server
            port:
              number: 80
        path: /graphql
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{ .Release.Name }}-web
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls-secret-{{ .Release.Name }}
status:
  loadBalancer: {}