domain: my-fbg.info         # For prod, use freeboardgames.org

images:
  imagePullPolicy: Never    # For prod, use Always
  web: fbg-web              # For prod, use freeboardgames/web
  fbgServer: fbg-server     # For prod, use freeboardgames/fbg-server

replicas:
  web: 2
  fbgServer: 2
  bgio: 2

fbgServer:
  jwtSecret: SECRET_TO_SIGN_JWT

postgresql:
  postgresqlPostgresPassword: PG_ROOT_PASSWORD
  postgresqlUsername: fbgUser
  postgresqlPassword: PG_DB_PASSWORD
  postgresqlDatabase: fbgDb
  service:
    port: 5432
  volumePermissions:
    enabled: true
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi

redis:
  auth:
    password: REDIS_FBG_PASSWORD